name: Code Quality Check

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  # 手動実行も可能にする
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install radon wily
          
      - name: Check cyclomatic complexity
        run: |
          # 複雑度が高すぎる関数をエラー表示（複雑度F以上でエラー）
          radon cc --min F game/ || echo "WARNING: 複雑度が非常に高い関数が見つかりました！"
          # 全体の複雑度レポート生成
          radon cc game/ -s > complexity_report.txt
          
      - name: Check raw metrics
        run: |
          # 行数が多すぎるファイルをチェック
          radon raw game/ -s > raw_metrics.txt
          python -c "
          import re
          with open('raw_metrics.txt', 'r') as f:
              content = f.read()
          # 500行以上のファイルを検出
          big_files = re.findall(r'(game[\\\\/][^\n]+)\n\s+LOC: (\d+)', content)
          big_files = [(f, int(loc)) for f, loc in big_files if int(loc) > 500]
          if big_files:
              print('WARNING: 以下のファイルは500行を超えています:')
              for file, loc in big_files:
                  print(f'  - {file}: {loc}行')
              exit(1)
          "
          
      - name: Upload reports as artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            complexity_report.txt
            raw_metrics.txt
            
      - name: Build wily report
        run: |
          wily build game/
          wily report 